version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-cdc-outbox
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abs
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d abs"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres-data:
    driver: local
